### ISSUE TITLE
Debug Package Control warnings

### ISSUE THREAD

**Issue by cheshire137** [LexLadiesCode/SublimeTextGistPlugin#12]
After symlinking the whole directory into your `Sublime Text 3/Packages` directory and opening Sublime Text, you'll see errors like these in the console:

```
Package Control: Unable to remove old directory LexLadiesGistCreator - deferring until next start
Package Control: Unable to remove directory for orphaned package LexLadiesGistCreator - deferring until next start
```

These... seem weird.

**Comment by summasmiff** [comment]
I think this is because we haven't installed our GistCreator via Package Control. Package Control has some default settings to clean up your package directory of directories and files that aren't installed. 

To remove these warnings, you can update your Package Control preferences to ignore our gist creator until we're done with it:
1. Open Package Control user settings by pressing `cmd-shift-P` and choosing Package Control > User Settings.
2. Add the following:

```
"dirs_to_ignore":
    [
        "LexLadiesGistCreator"
    ],
```
1. Restart Sublime Text. You should still be able to run our GistCreator, but that error will go away.
